clean:
	rm -f test*

test1:
	gcc -o test1 threadA_B.c -lpthread

test2:
	gcc -o test2 parent_child_thread1.c -lpthread

test3:
	gcc -o test3 parent_child_thread2.c -lpthread

test4:
	gcc -o test4 producer_and_consumer.c -lpthread

test5:
	gcc -o test5 signal_test.c -lpthread